# Generated by Django 4.1.4 on 2022-12-24 18:40

from django.db import migrations, models
import home.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=15)),
                ('link', models.CharField(max_length=200)),
                ('pos', models.IntegerField(default=0)),
                ('neg', models.IntegerField(default=0)),
                ('neu', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('username', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=15)),
                ('fname', models.CharField(max_length=15)),
                ('tid', models.CharField(max_length=15)),
                ('yid', models.CharField(max_length=15)),
                ('image', models.ImageField(default='', upload_to=home.models.upload_location)),
            ],
        ),
    ]
